import Image from 'next/image'
import { Inter } from 'next/font/google'
// import ManualHeader from '../../components/ManualHeader'
import Header from '../../components/Header'
import LotteryEntrance from '../../components/LotteryEntrance'

export default function Home() {
  return (
      <div>
       <title>Create Next App</title>
       <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <ManualHeader /> */}
        <Header />
        <div className="flex flex-row">
              <LotteryEntrance className="p-8" />
            </div>
      </div>
  )
}
